// Demo suppliers — 6 dummy vendors across 4 regions.
// Replace these with your own once the template is forked.

export const demoSuppliers = [
  {
    id: 'sup-1',
    supplier_code: 'SUP-001',
    supplier_name: 'Acme Manufacturing Co',
    supplier_type: 'OEM',
    access_model: 'direct',
    payment_terms_fg: '30 days',
    payment_terms_pkg: '30 days',
    primary_contact_name: 'Lim Wei Han',
    primary_contact_email: 'wlim@acme-mfg.example',
    primary_contact_phone: '+60 12 345 6789',
    primary_contact_channel: 'email',
    secondary_contact_name: null,
    secondary_contact_email: null,
    secondary_contact_phone: null,
    secondary_contact_channel: null,
    notes: 'Primary FG manufacturer · Kuala Lumpur facility',
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 'sup-2',
    supplier_code: 'SUP-002',
    supplier_name: 'Pacific Foods Sdn Bhd',
    supplier_type: 'OEM',
    access_model: 'direct',
    payment_terms_fg: '60 days',
    payment_terms_pkg: '60 days',
    primary_contact_name: 'Sarah Tan',
    primary_contact_email: 'sarah@pacificfoods.example',
    primary_contact_phone: '+60 19 222 3344',
    primary_contact_channel: 'whatsapp',
    secondary_contact_name: null,
    secondary_contact_email: null,
    secondary_contact_phone: null,
    secondary_contact_channel: null,
    notes: 'Penang facility · health drinks specialist',
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'sup-3',
    supplier_code: 'SUP-003',
    supplier_name: 'Global Pack Co',
    supplier_type: 'Packaging',
    access_model: 'agent',
    payment_terms_fg: null,
    payment_terms_pkg: '45 days',
    primary_contact_name: 'David Chen',
    primary_contact_email: 'david@globalpack.example',
    primary_contact_phone: '+86 138 8000 1234',
    primary_contact_channel: 'wechat',
    secondary_contact_name: 'Tina Wong',
    secondary_contact_email: 'tina@globalpack.example',
    secondary_contact_phone: '+86 138 8000 5678',
    secondary_contact_channel: 'wechat',
    notes: 'Shenzhen-based packaging supplier · paper boxes',
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2025-02-10T00:00:00Z',
  },
  {
    id: 'sup-4',
    supplier_code: 'SUP-004',
    supplier_name: 'Eastern Bottle Works',
    supplier_type: 'Packaging',
    access_model: 'direct',
    payment_terms_fg: null,
    payment_terms_pkg: '30 days',
    primary_contact_name: 'Ahmad Faiz',
    primary_contact_email: 'ahmad@ebw.example',
    primary_contact_phone: '+60 17 888 9900',
    primary_contact_channel: 'email',
    secondary_contact_name: null,
    secondary_contact_email: null,
    secondary_contact_phone: null,
    secondary_contact_channel: null,
    notes: 'Johor Bahru · PET bottles 100ml-250ml',
    created_at: '2025-02-15T00:00:00Z',
    updated_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'sup-5',
    supplier_code: 'SUP-005',
    supplier_name: 'PrintMax Labels',
    supplier_type: 'Packaging',
    access_model: 'direct',
    payment_terms_fg: null,
    payment_terms_pkg: '30 days',
    primary_contact_name: 'Jenny Ng',
    primary_contact_email: 'jenny@printmax.example',
    primary_contact_phone: '+60 12 666 7788',
    primary_contact_channel: 'whatsapp',
    secondary_contact_name: null,
    secondary_contact_email: null,
    secondary_contact_phone: null,
    secondary_contact_channel: null,
    notes: 'Klang · labels and foil printing',
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'sup-6',
    supplier_code: 'SUP-006',
    supplier_name: 'Wellness Distributor Pte Ltd',
    supplier_type: 'OEM',
    access_model: 'agent',
    payment_terms_fg: '90 days',
    payment_terms_pkg: null,
    primary_contact_name: 'Michael Lee',
    primary_contact_email: 'michael@wellness-dist.example',
    primary_contact_phone: '+65 9123 4567',
    primary_contact_channel: 'email',
    secondary_contact_name: null,
    secondary_contact_email: null,
    secondary_contact_phone: null,
    secondary_contact_channel: null,
    notes: 'Singapore HQ · supplements OEM',
    created_at: '2025-03-15T00:00:00Z',
    updated_at: '2025-03-15T00:00:00Z',
  },
]
